name: widgets_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  dio: ^5.5.0+1
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  go_router: ^14.2.7
  intl: ^0.18.0
  lottie: ^3.1.2
  open_filex: ^4.5.0
  path: ^1.8.3
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  syncfusion_flutter_charts: ^26.2.14

dev_dependencies:
  animate_do: ^3.3.4
  flutter_lints: ^4.0.0
  flutter_riverpod: ^2.6.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/ternium_acero_background.png
  - assets/images/
